import Nav from '@/components/Nav'
import './globals.css'
import { Poppins } from 'next/font/google'
import Footer from '../components/Footer'

import { StrictMode } from 'react';




const inter = Poppins({ 
  subsets: ['latin'],
  weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
  
    <html lang="pl">
      {/* <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script> */}
       
        <body className={inter.className}>
          
          <Nav></Nav>
          {children}
          <Footer></Footer>
        </body>
       
    </html>
  )
}
